# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
np.__version__


'2.3.5'

In [4]:
np.version.short_version

'2.3.5'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [19]:
a = np.random.random((2,3,5))
a

array([[[0.14731596, 0.76823178, 0.93322861, 0.40546734, 0.99569379],
        [0.76081704, 0.90042077, 0.57112234, 0.08286953, 0.84391919],
        [0.31276148, 0.94015076, 0.10444886, 0.83116048, 0.96085221]],

       [[0.10327849, 0.92329839, 0.15334723, 0.36707383, 0.63982493],
        [0.30203267, 0.11968738, 0.93047281, 0.49505917, 0.83903137],
        [0.71217572, 0.87395049, 0.95466404, 0.53940878, 0.28396981]]])

In [21]:
a = np.random.randint(0, 100,(2,3,5))
print(a)


[[[83 77 92 27 58]
  [54 65 30 86 12]
  [93 33 91 32 91]]

 [[23 17 90  1 43]
  [54 99 91 30 56]
  [44 34 70 37 64]]]


In [ ]:
a = np.random.randn(2, 3, 5)


[[[-0.30042017 -1.54643501 -0.65561299 -0.79757646 -0.17885689]
  [-0.20486884 -1.94784391 -1.02270524 -0.22922593  0.77987929]
  [ 2.28089021  0.31406606  0.55186346 -0.07648302  0.18902502]]

 [[-2.42803548 -1.35822616 -1.99457129  0.22438587  0.47473325]
  [ 1.69779344 -1.24494174 -0.79648955 -0.03557356 -0.58006464]
  [-0.21544812  0.98053974  2.06761544 -0.9726319  -0.45971005]]]



### 4. Print a.


In [24]:
### [your code here]
print(a)

[[[-0.30042017 -1.54643501 -0.65561299 -0.79757646 -0.17885689]
  [-0.20486884 -1.94784391 -1.02270524 -0.22922593  0.77987929]
  [ 2.28089021  0.31406606  0.55186346 -0.07648302  0.18902502]]

 [[-2.42803548 -1.35822616 -1.99457129  0.22438587  0.47473325]
  [ 1.69779344 -1.24494174 -0.79648955 -0.03557356 -0.58006464]
  [-0.21544812  0.98053974  2.06761544 -0.9726319  -0.45971005]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [39]:
### [your code here]
b = np.ones((5,2,3))



### 6. Print b.


In [38]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [37]:
def get_size(a,b):
    if a.size == b.size:
        return a.size
    else:
        return b.size
    
print(get_size(a,b))

    

30


In [46]:
print(a)

[[[87 12  8 81 91]
  [55 42 30 98 60]
  [95 70  0 70 47]]

 [[54 15 59 98 23]
  [12  7 64 51 85]
  [52 62 79 82 26]]]


In [51]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 8. Are you able to add a and b? Why or why not?


In [48]:
### [your code here]
Incompatible Shapes (Error)



SyntaxError: invalid syntax (2049111793.py, line 2)



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [87]:
### [your code here]
c = np.transpose(b, (1, 2, 0)).shape

In [88]:
print(c)

(2, 3, 5)


In [55]:
import Handson as hd

In [92]:
hd.numpy_info(c)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30


In [56]:
hd.numpy_info(a)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [97]:
### [your code here]
a = np.random.randn(2, 3, 5)
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)

d = sum(a,c)

print(d.shape)




(2, 3, 5)


In [98]:
print(c.size)

30



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [99]:
### [your code here]
print(a)
print(d)


[[[ 0.49233837  0.14457085  0.63524883  1.16131314  0.14076981]
  [ 0.4650748  -1.63559604  0.22478275  0.25930513  1.04884664]
  [-1.62420922  0.37140704 -0.27109216  1.66812131 -0.67109995]]

 [[-0.16149851  1.48072955  0.1317407   0.27235145  0.85465809]
  [ 1.57112444  0.37711015  1.75951468  0.95927436 -0.83740733]
  [ 2.38457559 -0.70992314  1.62176924 -0.74036046 -0.65147419]]]
[[[ 1.33083986  2.6253004   1.76698952  2.43366459  1.99542789]
  [ 3.03619924 -0.2584859   2.98429743  2.21857949  1.21143931]
  [ 1.76036636  0.6614839   2.35067708  1.92776086 -0.32257414]]

 [[ 1.33083986  2.6253004   1.76698952  2.43366459  1.99542789]
  [ 3.03619924 -0.2584859   2.98429743  2.21857949  1.21143931]
  [ 1.76036636  0.6614839   2.35067708  1.92776086 -0.32257414]]]



### 12. Multiply a and c. Assign the result to e.


In [100]:
### [your code here]
e = np.multiply(a,c)

In [101]:
type(e)

numpy.ndarray

In [103]:
hd.numpy_info(e)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30




### 13. Does e equal to a? Why or why not?


In [104]:
### [your code here]
result = e == a





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [107]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



In [110]:
print(f"d_max = {d_max:.4f}")

d_max = 3.0362


In [111]:
print(f"d_min = {d_min:.4f}")


d_min = -0.3226


In [112]:
print(f"d_mean = {d_mean:.4f}")

d_mean = 1.7148



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [120]:
hd.numpy_info(d)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30


In [130]:
### [your code here]
f = np.empty(d.shape,dtype='U1')







### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [131]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            v = d[i][j][k]
            if v == d_min:
                f[i][j][k] = 0
            elif v == d_max:
                f[i][j][k] = 100
            elif v == d_mean:
                f[i][j][k] = 50
            elif d_min < v < d_mean:
                f[i][j][k] = 25
            elif d_mean < v < d_max:
                f[i][j][k] = 75







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [132]:
### [your code here]
print(d)
print(f)


[[[ 1.33083986  2.6253004   1.76698952  2.43366459  1.99542789]
  [ 3.03619924 -0.2584859   2.98429743  2.21857949  1.21143931]
  [ 1.76036636  0.6614839   2.35067708  1.92776086 -0.32257414]]

 [[ 1.33083986  2.6253004   1.76698952  2.43366459  1.99542789]
  [ 3.03619924 -0.2584859   2.98429743  2.21857949  1.21143931]
  [ 1.76036636  0.6614839   2.35067708  1.92776086 -0.32257414]]]
[[['2' '7' '7' '7' '7']
  ['1' '2' '7' '7' '2']
  ['7' '2' '7' '7' '0']]

 [['2' '7' '7' '7' '7']
  ['1' '2' '7' '7' '2']
  ['7' '2' '7' '7' '0']]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [133]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            v = d[i][j][k]
            if v == d_min:
                f[i][j][k] = 'A'
            elif v == d_max:
                f[i][j][k] = 'E'
            elif v == d_mean:
                f[i][j][k] = 'C'
            elif d_min < v < d_mean:
                f[i][j][k] = 'B'
            elif d_mean < v < d_max:
                f[i][j][k] = 'D'